apiVersion: v1
kind: Service
metadata:
  name: isamwrprp2
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 80
      name: isamwrprp2
      protocol: TCP
      nodePort: 30448
  selector:
    app: isamwrprp2

