apiVersion: apps/v1
kind: Deployment
metadata:
  name: isamruntime
  labels:
    app: isamruntime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isamruntime
  template:
    metadata:
      labels:
        app: isamruntime
    spec:
      volumes:
        - name: isamconfig
          emptyDir: {}
        - name: isamruntime-logs
          emptyDir: {}
      containers:
        - name: isamruntime
          image: store/ibmcorp/isam:9.0.7.1_IF2
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /var/shared
              name: isamconfig
            - mountPath: /var/application.logs
              name: isamruntime-logs
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_RESOURCE
          env:
            - name: SERVICE
              value: runtime
            - name: CONTAINER_TIMEZONE
              value: Asia/Kolkata
            - name: AUTO_RELOAD_FREQUENCY
              value: "5"
            - name: CONFIG_SERVICE_URL
              value: https://isamconfig:9443/shared_volume
            - name: CONFIG_SERVICE_USER_NAME
              value: cfgsvc
            - name: CONFIG_SERVICE_USER_PWD
              valueFrom:
                secretKeyRef:
                  name: configreader
                  key: cfgsvcpw
      imagePullSecrets:
        - name: dockerlogin
---
apiVersion: v1
kind: Service
metadata:
  name: isamruntime
spec:
  type: NodePort
  ports:
    - port: 443
      name: isamruntime
      protocol: TCP
      nodePort: 30447
  selector:
    app: isamruntime

